name: Conty CI

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: 'false'

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: utils.yml
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /opt

      - name: Build Conty
        run: |
          if [ -f /opt/Utils/utils.tar.gz ]; then
              cp /opt/Utils/* .
          fi

          chmod +x create-arch-bootstrap_python.sh create-conty.sh
          sudo ./create-arch-bootstrap_python.sh && sudo cp -r ./applications/* /home/runner/work/conty/conty/root.x86_64/usr/share/applications/ && sudo cp -r ./icons/* /home/runner/work/conty/conty/root.x86_64/usr/share/pixmaps/ && sudo cp -r ./lib/* /home/runner/work/conty/conty/root.x86_64/usr/lib/ && ./create-conty.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Conty
          path: conty.sh
